# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arrayVis.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 949)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bblsort = QtWidgets.QPushButton(self.centralwidget)
        self.bblsort.setGeometry(QtCore.QRect(0, 190, 141, 41))
        self.bblsort.setObjectName("bblsort")
        self.done = QtWidgets.QPushButton(self.centralwidget)
        self.done.setGeometry(QtCore.QRect(380, 90, 171, 51))
        self.done.setObjectName("done")
        self.insertsort = QtWidgets.QPushButton(self.centralwidget)
        self.insertsort.setGeometry(QtCore.QRect(150, 190, 151, 41))
        self.insertsort.setObjectName("insertsort")
        self.fusionsort = QtWidgets.QPushButton(self.centralwidget)
        self.fusionsort.setGeometry(QtCore.QRect(310, 190, 151, 41))
        self.fusionsort.setObjectName("fusionsort")
        self.quicksort = QtWidgets.QPushButton(self.centralwidget)
        self.quicksort.setGeometry(QtCore.QRect(480, 190, 161, 41))
        self.quicksort.setObjectName("quicksort")
        self.selectsort = QtWidgets.QPushButton(self.centralwidget)
        self.selectsort.setGeometry(QtCore.QRect(660, 190, 151, 41))
        self.selectsort.setObjectName("selectsort")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(520, 10, 441, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.done_2 = QtWidgets.QPushButton(self.centralwidget)
        self.done_2.setGeometry(QtCore.QRect(570, 90, 171, 51))
        self.done_2.setObjectName("done_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 370, 311, 261))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 230, 111, 101))
        self.label.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 310, 121, 61))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(100, 120, 160, 22))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(1000)
        self.horizontalSlider.setProperty("value", 1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 60, 261, 51))
        self.label_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 100, 71, 51))
        self.label_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 71, 51))
        self.label_5.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.formule = QtWidgets.QPushButton(self.centralwidget)
        self.formule.setGeometry(QtCore.QRect(190, 260, 131, 51))
        self.formule.setObjectName("formule")
        self.illustration = QtWidgets.QPushButton(self.centralwidget)
        self.illustration.setGeometry(QtCore.QRect(350, 260, 131, 51))
        self.illustration.setObjectName("illustration")
        self.lien = QtWidgets.QPushButton(self.centralwidget)
        self.lien.setGeometry(QtCore.QRect(510, 260, 131, 51))
        self.lien.setObjectName("lien")
        self.video = QtWidgets.QPushButton(self.centralwidget)
        self.video.setGeometry(QtCore.QRect(660, 260, 131, 51))
        self.video.setObjectName("video")
        self.picViewer = QtWidgets.QLabel(self.centralwidget)
        self.picViewer.setGeometry(QtCore.QRect(470, 330, 511, 291))
        self.picViewer.setText("")
        self.picViewer.setObjectName("picViewer")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(490, 0, 20, 71))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 60, 981, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 160, 981, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 240, 1011, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(350, 70, 20, 101))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(760, 70, 20, 101))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(0, 310, 991, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(330, 320, 20, 301))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 650, 701, 31))
        self.label_6.setStyleSheet("font-size:14px;\n"
"font: bold;")
        self.label_6.setObjectName("label_6")
        self.input = QtWidgets.QLineEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(10, 10, 461, 51))
        self.input.setObjectName("input")
        self.triArbre = QtWidgets.QPushButton(self.centralwidget)
        self.triArbre.setGeometry(QtCore.QRect(820, 190, 151, 41))
        self.triArbre.setObjectName("triArbre")
        self.graph = QtWidgets.QPushButton(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(810, 260, 131, 51))
        self.graph.setObjectName("graph")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(180, 330, 101, 31))
        self.save.setObjectName("save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bblsort.setText(_translate("MainWindow", "Bubble sort"))
        self.done.setText(_translate("MainWindow", "Verify"))
        self.insertsort.setText(_translate("MainWindow", "Insert sort"))
        self.fusionsort.setText(_translate("MainWindow", "Merge sort"))
        self.quicksort.setText(_translate("MainWindow", "Quick sort"))
        self.selectsort.setText(_translate("MainWindow", "Selection sort"))
        self.textBrowser.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Zone d\'information</span></p></body></html>"))
        self.done_2.setText(_translate("MainWindow", "Visualisation"))
        self.textBrowser_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Final result :</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Info"))
        self.label_2.setText(_translate("MainWindow", "Information"))
        self.label_3.setText(_translate("MainWindow", "Animation speed"))
        self.label_4.setText(_translate("MainWindow", "Slow"))
        self.label_5.setText(_translate("MainWindow", "Fast"))
        self.formule.setText(_translate("MainWindow", "Formula"))
        self.illustration.setText(_translate("MainWindow", "Illustration"))
        self.lien.setText(_translate("MainWindow", "More info"))
        self.video.setText(_translate("MainWindow", "Video"))
        self.label_6.setText(_translate("MainWindow", "Project of Semeh Chriha | GI1S3 "))
        self.triArbre.setText(_translate("MainWindow", "Tree sort"))
        self.graph.setText(_translate("MainWindow", "Graph"))
        self.save.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
